# Azure Vote UI controls
title: "Azure Vote App"
value1: Cats
value2: Dogs

# Service controls
serviceName: azure-vote-front
serviceType: LoadBalancer

redis:
    image: redis

image:
    repository: edsa14
    name: azure-vote-front
    tag: v1
